#+TITLE:  Literacy Narrative

# Aim for 1,000 words of content

I am two kinds of writer: a writer inside school, an academic writer,
and a writer outside school, a journal writer, letter writer,
essayist, and novelist. Not a poet, never poetry, even though my mom
wants me to write her one and she just had a stroke so time is running
out.

# What if I connect my mom's stroke and poetry? Reluctance to write a
# paper and my reluctance to write a poem for my mom? Both are because
# I am afraid of feedback and feeling like a bad writer...and maybe I
# can connect my dad's feedback of my poem to the teachers' feedback
# of my essays? Come back to this.

When I think of my academic writing, or when I think of myself as a
writer my position as a student always comes first. It's what I think
about when I think of myself as a writer. No matter how well acclaimed
my novel might become (if I ever publish it), I will still think of
myself as a struggling paper writer first. I think of Ms. Bierbower's
class in 11th grade. I took honors English because I loved to read and
I was told I had talent as a writer so the class should show me new
things that I would enjoy learning about. I think she was a good
teacher, but what I remember most was not writing the papers. I would
receive the assignment with fear, then sit in anxiety as I put it off
and off and off...maybe part of it was that I struggled to do the
daily homework too. By anyway, The time would come to turn it in and I
would sit there paralyzed as she would come to our desks, pause by
mine, sigh when I didn't look up let alone turn something in, and then
move on.

Later, my parents would find out that I hadn't done my work and they
would get mad as usual. "Why can't you just do your work?" Then the
worst part would come: I'd have to, HAVE to, sit in front of the
computer with my English textbook and assignment out and type the
paper from start to finish. The blank page still horrifies me. I'd
spend 30 minutes on the heading, font, spacing, etc. Then I would hate
every word I wrote...

# I also give speeches, that's another kinds of writing, remember
# that.

...My attitude would shift from "Just get something down" to "Just
finish it, who cares what it looks like, just get it done." Writing
was a chore, a transaction. I was never invested in what I wrote. Then
I would turn it in late and get a B or B+ on it. Instead of
encouraging me that I had writing ability and not to be so afraid of
it, instead this made me think that I was good at doing things at the
last minute, or that the teacher was an easy grader, and I never
changed my ways.

Why was writing so hard for me? I think it was because I hated seeing
my own words on the page. It made me uncomfortable because I felt like
I was full of it, like it was BS, and I was inferior to other writers
I liked to read. It wasn't until I gave myself permission to write a
bad first draft that writing stopped becoming so painful. Now it's not
a big deal to write papers...but still...

I like to write though. Every day I keep a diary of my thoughts,
ideas, tasks, dreams, and important events of the day. I like that ---
there's no hesitation to open my journal and write my thoughts, even
though it is so hard to write a paper! I think it comes down to
feedback: no one will grade my journal. Grades are hard. There's no
such thing as a perfect score with grades, and that's hard too. With
journals, scores don't exist so failure doesn't exist either. And yet
it's hard to write my novel. I think that's because there is someone
judging me: my original idea. I have to measure up to my inspiration
and yet the act of writing makes an imperfect representation to my
inspiration: no wonder it's hard.

I like writing stories. I'm writing a fantasy novel right now. I only
have 8 pages though! I want to have 50 by the end of the month. I must
write it. It's a good story, and it honors those I care about in my
life. Writing allows me literally to create new worlds.

# Restarting with a new order here...

This is the story of my writing experiences. So I guess I should tell
it in order. I started out as a handwriting writer. I cared a great
deal about how shapely my letters were. We all remember the
three-lined practice paper, right? And then there was cursive: writing
like an adult. Writing was a mark of age and sophistication. It was a
honorable skill.

And yet it was fun too. I remember in third grade we received writing
assignments where we had a picture and a bunch of lines underneath and
we'd have to write a story that fit the picture. The one I remember is
of a mouse dressed like a theif holding a bag of money. I really,
REALLY enjoyed those assignments. Why though? What as so special? I
think it was because the writing made my imagination real, and making
my own story gave me power over what I read. I loved being able to
make decisions about what would happen to the characters. This would
often turn comic or dark and the teacher would have to talk to me
about including too much farting or asking if everything was ok if I
wrote about how a plane crashed into the characters which sent the
earth out of its orbit and into the sun, killing everyong on
earth. Writing was play at this time, it was a combination of
something good to do that people respected you for and also something
easy and fun. All this changed in high school.

# Organize here by moving high school writing, then follow it up with
# personal writing, then include a paragraph about writing for the
# future. 
































